meta_name: "NaniMiru name"
meta_title: "NaniMiru name - choosing shouldn't be a chore"
meta_description: "A bootcamp's final project that allows a group of people to easily and quickly come to consensus which movie to watch."
meta_image: "meta.png" # should exist in `app/assets/images/`
